### ISSUE TITLE
npm-shrinkwrap requires i@0.3.2, which is unpublished

### ISSUE THREAD

**Issue by terinjokes** [mojotech/pioneer#342]
The package version `i@0.3.2` has been unpublished (see: https://registry.npmjs.org/i/), but the npm-shrinkwrap.json file here continues to request it, even though pioneer's package.json lists 0.3.x.

Can this be updated, or can I be given publish + commit bits to do minor fixes?

**Comment by samccone** [comment]
cc @cpjolicoeur ^

**Comment by samccone** [comment]
cc @wkf ^^

**Comment by wkf** [comment]
Thanks @terinjokes, I've merged it. Can you confirm all is well? I'm going to close the issue, we can reopen if necessary. Thanks!

**Comment by samccone** [comment]
I chatted with @terinjokes out of band, and he expressed that he is willing to take over maintenance of this package given that their team is still using pioneer. 

I am +1 on the idea of giving him commit / publish access.

**Comment by wkf** [comment]
Can you confirm that in-band @terinjokes ?

**Comment by terinjokes** [comment]
@wkf yes, as mentioned in the ticket, we're willing to do maintenance, as needed.

**Comment by julienR2** [comment]
I'm still getting the "fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz" error even after the last change.. Any idea ?

**Comment by dealloc** [comment]
I'm still receiving fetch errors
![1465119679](https://cloud.githubusercontent.com/assets/2164354/15804708/73dbe92e-2b12-11e6-8175-daf46e7c2d49.png)
